language: node_js
node_js:
  - "stable"

env:
  global:
    - DATABASE_URL="postgres://admin:admin123@localhost:5432/auctioneer_test"

install: npm install

services:
  - postgresql

notifications:
  email: false

before_script:
  - psql -c "CREATE DATABASE auctioneer_test;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres

script: node manageDB createUsersTable && npm test

cache:
  directories:
    - "node_modules"
    - "test"
branches:
  only:
    - develop
