dist: bionic
language: node_js
node_js:
  - "stable"

env:
  global:
    - NODE_ENV=test
    - TEST_DATABASE_URL="postgres://admin:admin123@localhost:5432/auctioneer_test"
    - PORT=4000
    - SECRET_KEY="superpower"

install: npm install

services:
  - postgresql

notifications:
  email: false

before_script:
  - psql -c "CREATE DATABASE auctioneer_test;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres
  - node manageDB createUsersTable
  - node manageDB createOwnersTable
  - node manageDB createCategoriesTable
  - node manageDB createItemsTable

script: npm test

cache:
  directories:
    - "node_modules"
    - "test"
