language: node_js
node_js:
  - "stable"

env:
  global:
    - DATABASE_URL="postgres://admin:admin123@localhost:5432/auctioneer_test"
    - NODE_ENV=test

install: npm install

services:
  - postgresql

notifications:
  email: false

before_script:
  - psql -c "CREATE DATABASE auctioneer_test;" -U postgres
  - psql -c "CREATE USER admin WITH PASSWORD 'admin123';" -U postgres
  - psql -c "CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email VARCHAR(50) UNIQUE NOT NULL,password VARCHAR(100) NOT NULL,dateCreated TIMESTAMP,dateModified TIMESTAMP);" -U postgres


script: node manageDB createOwnersTable && node manageDB createCategoriesTable && node manageDB createItemsTable && npm test


cache:
  directories:
    - "node_modules"
    - "test"
branches:
  only:
    - develop
