language: node_js
node_js:
  - "stable"

env:
  global:
    - DATABASE_URL="postgres://postgres@localhost:5432/auctioneer_test"
    - NODE_ENV=test
    - PORT=4000
    - SECRET_KEY="superpower"

install: npm install

services:
  - postgresql

notifications:
  email: false

before_script:
  - psql -c "CREATE DATABASE auctioneer_test;" -U postgres


script:node manageDB createUsersTable && node createOwnersTable && node manageDB createCategoriesTable && node manageDB createItemsTable && npm test


cache:
  directories:
    - "node_modules"
    - "test"
branches:
  only:
    - develop
